name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run tests
      run: mvn test

    - name: Send email notification
      if: failure() || success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ecxe keve mvvl bzue
        subject: Build ${{ job.status }} for ${{ github.repository }}
        body: |
          The GitHub Actions build has completed.
          - Repository: ${{ github.repository }}
          - Workflow: ${{ github.workflow }}
          - Job: ${{ github.job }}
          - Commit: ${{ github.sha }}
          - Author: ${{ github.actor }}
          - Status: ${{ job.status }}
        to: zakhan23.zk@gmail.com
        from: Maven
